import './globals.css';
import MonitorImage from './ui/MonitorImage';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <main>
          <MonitorImage />
          { children }
        </main>
      </body>
    </html>
  );
}
